<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-08T15:54:06 IST" name="ParellelTestingSuite" finished-at="2023-03-08T15:54:16 IST" duration-ms="10640">
    <groups>
    </groups>
    <test started-at="2023-03-08T15:54:06 IST" name="Test" finished-at="2023-03-08T15:54:16 IST" duration-ms="10640">
      <class name="projectFolder.TC01_verify_LoginFunctionality">
        <test-method signature="verifyloginFunctionality()[pri:0, instance:projectFolder.TC01_verify_LoginFunctionality@7671cb68]" started-at="2023-03-08T15:54:06 IST" name="verifyloginFunctionality" finished-at="2023-03-08T15:54:16 IST" duration-ms="10592" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyloginFunctionality -->
      </class> <!-- projectFolder.TC01_verify_LoginFunctionality -->
      <class name="projectFolder.TC03_Addbagproduct">
        <test-method signature="addbagproduct()[pri:0, instance:projectFolder.TC03_Addbagproduct@3541cb24]" started-at="2023-03-08T15:54:06 IST" name="addbagproduct" finished-at="2023-03-08T15:54:16 IST" duration-ms="10021" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [3] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at projectFolder.TC03_Addbagproduct.addbagproduct(TC03_Addbagproduct.java:61)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addbagproduct -->
      </class> <!-- projectFolder.TC03_Addbagproduct -->
      <class name="projectFolder.TC02_verifyLogOutFunctionality">
        <test-method signature="verifyLogOutFunctionality()[pri:0, instance:projectFolder.TC02_verifyLogOutFunctionality@49dc7102]" started-at="2023-03-08T15:54:06 IST" name="verifyLogOutFunctionality" finished-at="2023-03-08T15:54:16 IST" duration-ms="10525" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogOutFunctionality -->
      </class> <!-- projectFolder.TC02_verifyLogOutFunctionality -->
    </test> <!-- Test -->
  </suite> <!-- ParellelTestingSuite -->
</testng-results>
